/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024v2;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author hoffs
 */
public class HållbarhetsMål extends javax.swing.JFrame {
    private InfDB idb;
    private String InloggadHandlaggare;

    /**
     * Creates new form HållbarhetsMål
     */
    public HållbarhetsMål(InfDB idb) {
        this.idb = idb;
        this.InloggadHandlaggare = InloggadHandlaggare;
        this.setVisible(true);
        initComponents();
        
                try {
            String sqlFraga = "SELECT * FROM hallbarhetsmal";
            ArrayList<HashMap<String, String>> ListaHållbarhetsMål = idb.fetchRows(sqlFraga);
            
                    // Skapa en modell för listan
            DefaultListModel<String> model = new DefaultListModel<>();
            
            System.out.println("Antal hållbarhetsmål: " + ListaHållbarhetsMål.size());

            // Loopa igenom resultaten och lägg till dem i listmodellen
            for (HashMap<String, String> rad : ListaHållbarhetsMål) {
                // Skapa en sträng med HTML-formatering för varje hållbarhetsmål
                String htmlFormattedItem = "<html><font color='green'><b>Namn:</b></font> " + rad.get("namn") + "<br>"
                                          + "<font color='blue'><b>Målnummer:</b></font> " + rad.get("malnummer") + "<br>"
                                          + "<font color='orange'><b>Beskrivning:</b></font> " + rad.get("beskrivning") + "<br>"
                                          + "<font color='red'><b>Prioritet:</b></font> " + rad.get("prioritet") + "</html>";
                model.addElement(htmlFormattedItem);
            }
                        // Skapa en JList med modellen
            JList<String> hållbarhetsMålLista = new JList<>(model);

            // Lägg till JList till en JScrollPane för att göra det möjligt att rulla
           JScrollPane scrollPane = new JScrollPane(hållbarhetsMålLista);
            scrollPane.setBounds(20, 40, 500, 300); // Ange position och storlek för JScrollPane
            
            // Lägg till JScrollPane till JFrame
            getContentPane().add(scrollPane);

            
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void gatillhandlaggarmeny() {
        this.dispose();
        HandläggarMeny handläggarMeny = new HandläggarMeny(idb, InloggadHandlaggare);
        handläggarMeny.setVisible(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHållbarhetsMål = new javax.swing.JLabel();
        btnGåTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHållbarhetsMål.setText("Hållbarhetsmålen");

        btnGåTillbaka.setText("Gå tillbaka");
        btnGåTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGåTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblHållbarhetsMål, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnGåTillbaka)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGåTillbaka)
                    .addComponent(lblHållbarhetsMål))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGåTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGåTillbakaActionPerformed
        gatillhandlaggarmeny();
    }//GEN-LAST:event_btnGåTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HållbarhetsMål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HållbarhetsMål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HållbarhetsMål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HållbarhetsMål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HållbarhetsMål(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGåTillbaka;
    private javax.swing.JLabel lblHållbarhetsMål;
    // End of variables declaration//GEN-END:variables
}