/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024v2;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author hoffs
 */
public class Inloggning extends javax.swing.JFrame {
    
    private final InfDB idb;
    private String ePost;

   
    public Inloggning(InfDB idb) {
        this.idb = idb;
        initComponents();
        lblFelmeddelande.setVisible(false);
        setSize(525,410);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        lblFelmeddelande = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        pfLosenord = new javax.swing.JPasswordField();
        btnGlomtLosenord = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblEpost.setText("Epost");
        getContentPane().add(lblEpost);
        lblEpost.setBounds(50, 60, 37, 16);

        lblLosenord.setText("Lösenord");
        getContentPane().add(lblLosenord);
        lblLosenord.setBounds(50, 97, 49, 16);

        tfEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEpostActionPerformed(evt);
            }
        });
        getContentPane().add(tfEpost);
        tfEpost.setBounds(126, 57, 139, 22);

        lblFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelande.setText("Felaktigt lösenord eller epost, vänligen försök igen");
        getContentPane().add(lblFelmeddelande);
        lblFelmeddelande.setBounds(60, 210, 300, 16);

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoggaIn);
        btnLoggaIn.setBounds(130, 150, 120, 23);

        pfLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfLosenordActionPerformed(evt);
            }
        });
        getContentPane().add(pfLosenord);
        pfLosenord.setBounds(126, 97, 139, 22);

        btnGlomtLosenord.setText("Glömt Lösenord");
        btnGlomtLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlomtLosenordActionPerformed(evt);
            }
        });
        getContentPane().add(btnGlomtLosenord);
        btnGlomtLosenord.setBounds(110, 180, 160, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hoffs\\OneDrive\\Bilder\\devgoalspic2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEpostActionPerformed
// Metod för att anställda ska kunna logga in
    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        
        String ePost = tfEpost.getText();
        String losen = pfLosenord.getText();
        String Text = lblFelmeddelande.getText();
        
        
        

        
        
        // Hämtar aid och lösenord från databasen som stämmer överens med epost
        try {
            String sqlFraga = "SELECT aid, losenord FROM anstalld WHERE epost = '" + ePost +"'";
            System.out.println(sqlFraga);
            HashMap<String, String> dbAnstalld = idb.fetchRow(sqlFraga);
            
           // Om lösen stämmer så loggas anställd in och inloggningsmenyn stängs ner
        if(dbAnstalld != null && losen.equals(dbAnstalld.get("losenord"))){
            // Hämta användarroll från en annan SQL-fråga
            String rollQuery = "SELECT aid, 'handlaggare' AS roll FROM handlaggare WHERE aid = '" + dbAnstalld.get("aid") + "' UNION " +
                               "SELECT aid, 'admin' AS roll FROM admin WHERE aid = '" + dbAnstalld.get("aid") + "'";
            HashMap<String, String> dbRoll = idb.fetchRow(rollQuery);
            
            // Om användaren har en roll
            if(dbRoll != null && dbRoll.containsKey("roll")){
                String roll = dbRoll.get("roll");
                
                // Beroende på rollen, öppna rätt meny
                if (roll.equals("admin")){
                    new AdminMeny(idb, ePost).setVisible(true);
                    this.setVisible(false);
                } else if (roll.equals("handlaggare")) {
                    new HandläggarMeny(idb, ePost).setVisible(true);
                
                    this.setVisible(false);
            }
             
            

             
            }
           
        }
        else {
            // Visa felmeddelande om användaren inte finns i databasen eller lösenordet är felaktigt
            lblFelmeddelande.setText("Felaktigt lösenord eller epost, vänligen försök igen.");
            lblFelmeddelande.setVisible(true);
            
            
            if (!Validering.valideraEpost(ePost)) {
   
    return;
}

if (!Validering.valideraLosenord(losen)) {
   
    return;
}
if (!Validering.valideraText(Text)) {
   
    return;
}
        }
        }
        catch (InfException ex) {
            System.out.println(ex.getMessage());
    }//GEN-LAST:event_btnLoggaInActionPerformed
        }
    private void pfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfLosenordActionPerformed

    private void btnGlomtLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlomtLosenordActionPerformed
        // TODO add your handling code here:
        GlömtLösenord GlomtLosenordFönster = new GlömtLösenord(idb);
        GlomtLosenordFönster.setVisible(true);
    }//GEN-LAST:event_btnGlomtLosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGlomtLosenord;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JPasswordField pfLosenord;
    private javax.swing.JTextField tfEpost;
    // End of variables declaration//GEN-END:variables
}
