/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024v2;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author livlagercrantz
 */
//Klassdeklaration
public class ProjektPåAvdelning extends javax.swing.JFrame {
private InfDB idb;
private HashMap <String, String> projektLista;
private javax.swing.JLabel lblFelmeddelande;
private String InloggadHandlaggare;
private String InloggadAdmin;
    /**
     * Creates new form ProjektPåAvdelning
     * @param idb
     * @param InloggadHandlaggare
     */

    public ProjektPåAvdelning(InfDB idb, String InloggadAdmin) {
        initComponents();
        this.idb = idb;
        this.projektLista = projektLista;
        this.lblFelmeddelande = new javax.swing.JLabel();
        this.InloggadAdmin = InloggadAdmin;
        lblFelmeddelande.setVisible(false);
        
        
        
      
    }
   
    
    private void projektstatus(String status) {
    String avdid = jTextField1.getText();

    try {
        String sqlFraga = "SELECT projekt.projektnamn, projekt.beskrivning, projekt.startdatum, projekt.slutdatum, projekt.kostnad, projekt.status, projekt.prioritet, projekt.projektchef, projekt.land " +
                          "FROM projekt " +
                          "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                          "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
                          "JOIN avdelning ON anstalld.avdelning = avdelning.avdid " +
                          "WHERE avdelning.avdid = " + avdid +
                          " AND projekt.status = '" + status + "'"; // Hämta projekt med den specifika statusen

        System.out.println(sqlFraga);

        List<HashMap<String, String>> projektLista = idb.fetchRows(sqlFraga);

        if (projektLista != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (HashMap<String, String> projekt : projektLista) {
                String projektnamn = projekt.get("projektnamn");
                String beskrivning = projekt.get("beskrivning");
                String startdatum = projekt.get("startdatum");
                String slutdatum = projekt.get("slutdatum");
                String kostnad = projekt.get("kostnad");
                String statusProjekt = projekt.get("status");
                String prioritet = projekt.get("prioritet");
                String projektchef = projekt.get("projektchef");
                String land = projekt.get("land");

                model.addRow(new Object[]{projektnamn, beskrivning, startdatum, slutdatum, kostnad, statusProjekt, prioritet, projektchef, land});
            }
        } else {
            // Inga projekt hittades för detta avdelnings-ID med den specifika statusen
            // Här kan du hantera detta fall, t.ex. visa ett meddelande för användaren
            System.out.println("Inga projekt med status '" + status + "' hittades för detta avdelningsID.");
        }
    } catch (InfException e) {
        // Hantera eventuella fel som kan uppstå vid databasåtkomst
        e.printStackTrace();
    }
}
    
    
    private ProjektPåAvdelning() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPlanerade = new javax.swing.JButton();
        btnPagaende = new javax.swing.JButton();
        btnAvslutade = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Projektnamn", "Beskrivning", "Startdatum", "Slutdatum", "Kostnad", "Status", "Prioritet", "Projektchef", "Land"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Din avdelnings tilldelade projekt");

        jLabel2.setText("Skriv i avdelningsID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Hämta projekt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gå tillbaka");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Inga projekt hittades för detta avdelningsID.");

        btnPlanerade.setText("Planerade");
        btnPlanerade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaneradeActionPerformed(evt);
            }
        });

        btnPagaende.setText("Pågående");
        btnPagaende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagaendeActionPerformed(evt);
            }
        });

        btnAvslutade.setText("Avslutade");
        btnAvslutade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvslutadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3)
                        .addGap(108, 108, 108)
                        .addComponent(btnAvslutade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(59, 59, 59)
                        .addComponent(btnPagaende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)))
                        .addGap(275, 275, 275)
                        .addComponent(btnPlanerade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPlanerade)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPagaende)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvslutade)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    String avdid = jTextField1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   String avdid = jTextField1.getText();

    try {
        String sqlFraga = "SELECT projekt.projektnamn, projekt.beskrivning, projekt.startdatum, projekt.slutdatum, projekt.kostnad, projekt.status, projekt.prioritet, projekt.projektchef, projekt.land " +
                          "FROM projekt " +
                          "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                          "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
                          "JOIN avdelning ON anstalld.avdelning = avdelning.avdid " +
                          "WHERE avdelning.avdid = " + avdid +
                          " ORDER BY projekt.status"; // Sortera projekten efter status

        System.out.println(sqlFraga);

        List<HashMap<String, String>> projektLista = idb.fetchRows(sqlFraga);

        if (projektLista != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (HashMap<String, String> projekt : projektLista) {
                String projektnamn = projekt.get("projektnamn");
                String beskrivning = projekt.get("beskrivning");
                String startdatum = projekt.get("startdatum");
                String slutdatum = projekt.get("slutdatum");
                String kostnad = projekt.get("kostnad");
                String status = projekt.get("status");
                String prioritet = projekt.get("prioritet");
                String projektchef = projekt.get("projektchef");
                String land = projekt.get("land");

                model.addRow(new Object[]{projektnamn, beskrivning, startdatum, slutdatum, kostnad, status, prioritet, projektchef, land});
            }
        } else {
            // Inga projekt hittades för detta avdelnings-ID
            // Här kan du hantera detta fall, t.ex. visa ett meddelande för användaren
            System.out.println("Inga projekt hittades för detta avdelningsID.");
        }
    } catch (InfException e) {
        // Hantera eventuella fel som kan uppstå vid databasåtkomst
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    //Metoden anropas för att öppna handläggarmenyn. This.dispose stänger det fönster man har öppet.
    //Efter det skapar man en ny instans av Handläggarmeny med inloggadHandläggare som paramenter
    // sedan gör man den nya handläggarmenyn synlig genom att använda setVisible(true).
    private void gatillHandlaggarMeny(){
        this.dispose();
        HandläggarMeny HandlaggareMenyFönster = new HandläggarMeny (idb, InloggadHandlaggare);
        HandlaggareMenyFönster.setVisible(false);
    }
    
    //När man klickar på knappen används metoden och man öppnar handläggarmenyn.
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gatillHandlaggarMeny();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPlaneradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaneradeActionPerformed
        projektstatus("planerat");
    }//GEN-LAST:event_btnPlaneradeActionPerformed

    private void btnAvslutadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvslutadeActionPerformed
       projektstatus("Avslutat");
    }//GEN-LAST:event_btnAvslutadeActionPerformed

    private void btnPagaendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagaendeActionPerformed
        projektstatus("Pågående");
    }//GEN-LAST:event_btnPagaendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektPåAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektPåAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektPåAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektPåAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektPåAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvslutade;
    private javax.swing.JButton btnPagaende;
    private javax.swing.JButton btnPlanerade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
