/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024v2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author jerry
 */
public class ÄndraProjektUppgifter extends javax.swing.JFrame {

    private InfDB idb;
    private HashMap<String, String> projektData;
    private JTextField txtProjektnamn, txtStartdatum, txtSlutdatum, txtBeskrivning, txtKostnad, txtStatus, txtPrioritet, txtLand;
    /**
     * Creates new form ÄndraProjektUppgifter
     * @param idb
     * @param projektData
     */
    public ÄndraProjektUppgifter(InfDB idb, HashMap<String, String> projektData) {
        this.idb = idb;
        this.projektData = projektData;
        initComponents();
        fyllFaltMedData();
    }

    public ÄndraProjektUppgifter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

private void fyllFaltMedData() {
        txtProjektnamn.setText(projektData.get("projektnamn"));
        txtStartdatum.setText(projektData.get("startdatum"));
        txtSlutdatum.setText(projektData.get("slutdatum"));
        txtBeskrivning.setText(projektData.get("beskrivning"));
        txtKostnad.setText(projektData.get("kostnad"));
        txtStatus.setText(projektData.get("status"));
        txtPrioritet.setText(projektData.get("prioritet"));
        txtLand.setText(projektData.get("land"));
    }

private void sparaProjekt() {
        try {
            String projektnamn = txtProjektnamn.getText();
            String startdatum = txtStartdatum.getText();
            String slutdatum = txtSlutdatum.getText();
            String beskrivning = txtBeskrivning.getText();
            String kostnad = txtKostnad.getText();
            String status = txtStatus.getText();
            String prioritet = txtPrioritet.getText();
            String land = txtLand.getText();

            String sqlUpdate = "UPDATE projekt SET "
                    + "projektnamn = '" + projektnamn + "', "
                    + "startdatum = '" + startdatum + "', "
                    + "slutdatum = '" + slutdatum + "', "
                    + "beskrivning = '" + beskrivning + "', "
                    + "kostnad = '" + kostnad + "', "
                    + "status = '" + status + "', "
                    + "prioritet = '" + prioritet + "', "
                    + "land = '" + land + "' "
                    + "WHERE pid = " + projektData.get("pid");

            idb.update(sqlUpdate);
            System.out.println("Projektet har uppdaterats.");
            this.dispose();
        } catch (InfException ex) {
            System.out.println("Ett fel inträffade vid uppdatering: " + ex.getMessage());
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÄndraProjektUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
